### PR TITLE
Prevents unknown prop ... on tag

### PR DESCRIPTION
**Pull request by jaulz**
Currently, the following warnings are printed:
- Unknown props `immutableData`, `renderEmpty`, `rowsDuringInteraction`, `sectionHeaderHasChanged`, `renderEmptyInList` on `<div>` tag. Remove these props from the element.
- Unknown prop `emptyText` on `<div>` tag. Remove this prop from the element.

These changes pass only the necessary props to the components.

### CODE REVIEW

**Comment by cooperka** [comment]
Hi @jaulz, thanks for the PR! Can you please add a description to help me understand why this change is needed?

**Comment by jaulz** [comment]
Hi @cooperka, the proposed changes are in fact not necessary from a functional point of view but they prevent unnecessary logs in the console because some props are superfluous. If you are fine with it, I would also adjust the tests.

**Comment by cooperka** [comment]
Hmm, it looks like tests are failing, and I can't seem to reproduce these warnings myself. Can you please give some sample code and let me know which React Native version you're using?

What do you mean by `<div>` tags (I don't think those are supported by React Native)?

**Comment by jaulz** [comment]
Sorry for the delay... I will take care of this as soon as I have time again. Just to give you a background: I use react-native-web and consequently see it for divs.

**Comment by cooperka** [comment]
Any updates on this @jaulz? No hurry just checking in :)

**Comment by jaulz** [comment]
Unfortunately not. Already set this as a reminder to the end of this month and hence it will still take a couple of weeks.

**Comment by jaulz** [comment]
@cooperka any idea why the build is failing? seems like React Native outputs something different on Travis?

**Comment by cooperka** [comment]
@jaulz it looks like you have conflicts with `master`; you should try rebasing (`git fetch origin; git rebase origin/master`) before running tests.

**Comment by jaulz** [comment]
@cooperka unfortunately this fork got bigger than I thought as it now also contains dependency updates and prettier. let me know what you think... if it's too much I can also check to divide it into multiple pull requests. thanks in advance!

**Comment by cooperka** [comment]
Hmm, I'd rather not have `prettier` as I already use `eslint`. If you think I should adjust the eslint rules, feel free to open a separate issue to discuss, but it should definitely be separate from this PR to keep things clean.

Do you mind rebasing your code and squashing commits so it's easier to understand what's going on? You have a lot of duplicate commit descriptions that should ideally be squashed together. Here's a guide if you want more info: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by jaulz** [comment]
Thanks for the link! Did not know that something like that exists 👍 
However, I will reopen a new pull request in a second which should be much cleaner :)

**Pull request closed without merging**
